CREATE TABLE IF NOT EXISTS vault_settings (name TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS vault_entries (id TEXT PRIMARY KEY, payload BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS vault_platforms (id TEXT PRIMARY KEY, payload BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS vault_sessions (id TEXT PRIMARY KEY, payload BLOB NOT NULL, last_active INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS vault_attempts (id TEXT PRIMARY KEY, count INTEGER NOT NULL, until_time INTEGER NOT NULL);
